[build]
  publish = "docs"
  # This tells Netlify NOT to run any install scripts
  command = ""

[build.environment]
  # This stops Netlify from looking for a Python environment
  NETLIFY_SKIP_PYTHON_INSTALL = "1"
  # This stops Netlify from looking for a Node.js environment
  NETLIFY_SKIP_NODE_INSTALL = "1"
